{% set name = "asyncstdlib" %}
{% set version = "3.10.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asyncstdlib-{{ version }}.tar.gz
  sha256: 4d836c65769761a47795667ed72f3de6cf4a25e480959f75fd91eb8eb5edc640

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - flit
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - typing_extensions

test:
  imports:
    - asyncstdlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxfischer2781/asyncstdlib
  summary: The missing async toolbox
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxfischer2781
