{% set name = "asyncstdlib" %}
{% set version = "3.10.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asyncstdlib-{{ version }}.tar.gz
  sha256: 474a3e73db68fb5a7fd416ac08354a6f137be39f56a4bc315662f1dfd580a4fb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - flit
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - typing_extensions

test:
  imports:
    - asyncstdlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxfischer2781/asyncstdlib
  summary: The missing async toolbox
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxfischer2781
