{% set name = "asyncstdlib" %}
{% set version = "3.10.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asyncstdlib-{{ version }}.tar.gz
  sha256: e9fc35e811d5b51d8fe3d17b62234b5e8e1a2513364228081cd88637b3a3506a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - flit-core
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - typing_extensions

test:
  imports:
    - asyncstdlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/maxfischer2781/asyncstdlib
  summary: The missing async toolbox
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxfischer2781
